# ==============================
# Local PostgreSQL
# ==============================

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Safe for development)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging (Detailed for debugging)
logging.level.com.taskflow=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Redis Local (Optional)
spring.data.redis.host=localhost
spring.data.redis.port=6379