# ==============================
# Render PostgreSQL (ENV VARIABLES)
# ==============================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Production Safe JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging Minimal
logging.level.root=INFO
logging.level.com.taskflow=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR

# Redis (if using Render Redis)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}